epochs: 5
batches_per_epoch: 500
lr: 1.0e-4
frame_loss_weight: 0.5
cross_loss_weight: 0.35
seed: 42
dino_checkpoint: "facebook/dinov3-vitl16-pretrain-lvd1689m"
dino_batch_split: 1
dino_img_dimension: 512

device: "cuda"
cuda_visible_devices: null

checkpoint_path: "weights/reid_transformer_latest.pt"
plot_path: "weights/loss_curve.png"

num_embeddings: 10
compute_eval_loss: true
compute_eval_accuracy: true
eval_loss_batches: 15
eval_max_embeddings: 1000
mini_eval_max_frame_embeddings: 1
eval_batch_size: 16

wandb_project: "open-vocab-mot-tests"
wandb_name: "low-dino-dim"
wandb_entity: null
no_wandb: false
run_initial_mini_eval: false

augmentation_config:
  enable: false
  crop_ratio_range: [0.9, 1.0]
  random_flip_prop: 0.5

  color_jitter_config:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  

use_nested_tensors: false
frame_transformer_dim: 1024
frame_contrastive_dim: 512
frame_num_heads: 8
frame_num_layers: 5
video_transformer_dim: 512
video_contrastive_dim: 512
video_num_heads: 4
video_num_layers: 3
dropout: 0.01

# frame_transformer_dim: 256
# frame_contrastive_dim: 256
# frame_num_heads: 4
# frame_num_layers: 3
# video_transformer_dim: 256
# video_contrastive_dim: 256
# video_num_heads: 4
# video_num_layers: 3
# dropout: 0.1

duke:
  eval_tasks: []
  mini_eval_tasks: []
  use_for_training: false
  weight: 1.0
  frames_per_video: 8
  people_per_batch: 16
  views_per_person: 4

whale:
  eval_tasks: []
  mini_eval_tasks: []
  use_for_training: false
  weight: 0.2
  frames_per_video: 4
  people_per_batch: 16
  views_per_person: 2
  min_num_images: 8

wildlife_subsets:
  - subset_dataset: 'AerialCattle2017'
    eval_tasks: []
    mini_eval_tasks: []
    use_for_training: false
    weight: 0.2
    frames_per_video: 4
    people_per_batch: 16
    views_per_person: 2
    min_num_images: 8

  - subset_dataset: 'ATRW'
    eval_tasks: []
    mini_eval_tasks: []
    use_for_training: false
    weight: 0.2
    frames_per_video: 4
    people_per_batch: 16
    views_per_person: 2
    min_num_images: 8

  - subset_dataset: 'CatIndividualImages'
    eval_tasks: []
    mini_eval_tasks: []
    use_for_training: false
    weight: 0.2
    frames_per_video: 4
    people_per_batch: 16
    views_per_person: 2
    min_num_images: 8

  - subset_dataset: 'DogFaceNet'
    eval_tasks: []
    mini_eval_tasks: []
    use_for_training: false
    weight: 0.2
    frames_per_video: 4
    people_per_batch: 16
    views_per_person: 2
    min_num_images: 8

  - subset_dataset: 'SeaTurtleID2022'
    eval_tasks: []
    mini_eval_tasks: []
    use_for_training: false
    weight: 0.2
    frames_per_video: 4
    people_per_batch: 16
    views_per_person: 2
    min_num_images: 8

  - subset_dataset: 'NyalaData'
    eval_tasks: []
    mini_eval_tasks: []
    use_for_training: false
    weight: 0.2
    frames_per_video: 4
    people_per_batch: 16
    views_per_person: 2
    min_num_images: 8

  # Test extrapolation by not training but doing eval
  - subset_dataset: 'CZoo'
    eval_tasks: []
    mini_eval_tasks: []
    use_for_training: false
    weight: 0.2
    frames_per_video: 4
    people_per_batch: 16
    views_per_person: 2
    min_num_images: 8

veri:
  eval_tasks: []
  mini_eval_tasks: []
  use_for_training: false
  weight: 1.0
  frames_per_video: 8
  people_per_batch: 16
  views_per_person: 4
  query_collapse_sequences: true

vrai:
  eval_tasks: []
  mini_eval_tasks: []
  use_for_training: false

hypersim:
  eval_tasks:
    - query_source: 'query'
      query_modality: 'video'
      gallery_source: 'gallery'
      gallery_modality: 'video'
  mini_eval_tasks:
    - query_source: 'query'
      query_modality: 'video'
      gallery_source: 'gallery'
      gallery_modality: 'video'
  use_for_training: true
  weight: 1.0
  frames_per_video: 8
  people_per_batch: 8
  views_per_person: 2
  val_split_ratio: 0.1
