from dotenv import load_dotenv
from pathlib import Path
import os

load_dotenv(verbose=True, override=True)

DUKEMTMC_VIDEO_REID_PATH = Path(os.getenv("DUKEMTMC_VIDEO_REID_PATH"))
DUKEMTMC_VIDEO_REID_SIDECAR_PATH = Path(os.getenv("DUKEMTMC_VIDEO_REID_SIDECAR_PATH"))
MARS_PATH = Path(os.getenv("MARS_PATH"))

WILDLIFE_DATASETS_BASE_PATH = Path(os.getenv("WILDLIFE_DATASETS_BASE_PATH"))

WHALE_DATASET_PATH = Path(os.getenv("WHALE_DATASET_PATH"))
WHALE_DATASET_SIDECAR_PATH = Path(os.getenv("WHALE_DATASET_SIDECAR_PATH"))

WILDLIFE_10K_PATH = Path(os.getenv("WILDLIFE_10K_PATH"))
WILDLIFE_10K_SIDECAR_PATH = Path(os.getenv("WILDLIFE_10K_SIDECAR_PATH"))

VERI_DATASET_PATH = Path(os.getenv("VERI_DATASET_PATH"))
VERI_DATASET_SIDECAR_PATH = Path(os.getenv("VERI_DATASET_SIDECAR_PATH"))

VRAI_DATASET_PATH = Path(os.getenv("VRAI_DATASET_PATH"))
VRAI_DATASET_SIDECAR_PATH = Path(os.getenv("VRAI_DATASET_SIDECAR_PATH"))

UNSUPERVISED_DATASET_INPUT_PATH = Path(os.getenv("UNSUPERVISED_DATASET_INPUT_PATH"))
UNSUPERVISED_DATASET_OUTPUT_PATH = Path(os.getenv("UNSUPERVISED_DATASET_OUTPUT_PATH"))